//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        public Announcement()
        {
            this.LendAHands = new HashSet<LendAHand>();
            this.UserComments = new HashSet<UserComment>();
            this.UserAccounts = new HashSet<UserAccount>();
        }
    
        public int AnnouncementID { get; set; }
        public string AnnouncementType { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateOfDemise { get; set; }
        public string Gender { get; set; }
        public string BaseLocation { get; set; }
        public string ExpiredLocation { get; set; }
        public byte[] Image { get; set; }
        public string AnnouncementText { get; set; }
        public int CreatedUserID { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> NumberOfShares { get; set; }
        public byte[] ContentImage { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public Nullable<int> RegretCount { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
        public virtual ICollection<LendAHand> LendAHands { get; set; }
        public virtual ICollection<UserComment> UserComments { get; set; }
        public virtual ICollection<UserAccount> UserAccounts { get; set; }
    }
}
