//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContributionDetail
    {
        public int LendAHandID { get; set; }
        public int ContributorID { get; set; }
        public decimal AmountContributed { get; set; }
        public System.DateTime ContributedDateTime { get; set; }
    
        public virtual LendAHand LendAHand { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
