//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyTree
    {
        public int UserID { get; set; }
        public string MemberFirstName { get; set; }
        public string MemberLastName { get; set; }
        public string Relationship { get; set; }
        public int UserUniqueIndex { get; set; }
        public int ParentChildLink { get; set; }
        public byte[] MemberImage { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DateOfDemise { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
