//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LendAHand
    {
        public LendAHand()
        {
            this.ContributionDetails = new HashSet<ContributionDetail>();
        }
    
        public int LendAHandID { get; set; }
        public int AnnouncementID { get; set; }
        public string LendAHandText { get; set; }
        public decimal AmountPledged { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual Announcement Announcement { get; set; }
        public virtual ICollection<ContributionDetail> ContributionDetails { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
