//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionMaster
    {
        public RegionMaster()
        {
            this.UserContactDetails = new HashSet<UserContactDetail>();
        }
    
        public int RegionID { get; set; }
        public string RegionName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<UserContactDetail> UserContactDetails { get; set; }
    }
}
