//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TermsMaster
    {
        public TermsMaster()
        {
            this.UserAccounts = new HashSet<UserAccount>();
        }
    
        public int TermsID { get; set; }
        public string TermText { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public byte[] CreatedTimeStamp { get; set; }
    
        public virtual ICollection<UserAccount> UserAccounts { get; set; }
    }
}
