//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timeline
    {
        public int UserID { get; set; }
        public string PostContent { get; set; }
        public int PostType { get; set; }
        public int Category { get; set; }
        public byte[] PostImage { get; set; }
        public string VideoLink { get; set; }
        public byte[] CreationTimeStamp { get; set; }
        public int TimelineID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string ToWhom { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
