//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserComment
    {
        public UserComment()
        {
            this.UserAccounts = new HashSet<UserAccount>();
        }
    
        public int CommentsID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int AnnouncementID { get; set; }
        public string CommentsText { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<bool> CreatedByAdmin { get; set; }
        public Nullable<bool> CreatedByCurrentUser { get; set; }
        public Nullable<bool> ModerationPending { get; set; }
        public Nullable<int> UpVoteCount { get; set; }
    
        public virtual Announcement Announcement { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        public virtual ICollection<UserAccount> UserAccounts { get; set; }
    }
}
