//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public UserAccount()
        {
            this.Announcements = new HashSet<Announcement>();
            this.FamilyTrees = new HashSet<FamilyTree>();
            this.LendAHands = new HashSet<LendAHand>();
            this.Timelines = new HashSet<Timeline>();
            this.ContributionDetails = new HashSet<ContributionDetail>();
            this.Nominees = new HashSet<Nominee>();
            this.Nominees1 = new HashSet<Nominee>();
            this.UserComments = new HashSet<UserComment>();
            this.UserContactDetails = new HashSet<UserContactDetail>();
            this.UserPersonalDetails = new HashSet<UserPersonalDetail>();
            this.UserComments1 = new HashSet<UserComment>();
            this.Announcements1 = new HashSet<Announcement>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string EmailID { get; set; }
        public bool EmailVerified { get; set; }
        public string UserPassword { get; set; }
        public bool Active { get; set; }
        public int TermsID { get; set; }
        public System.DateTime AgreedToTermsDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    
        public virtual ICollection<Announcement> Announcements { get; set; }
        public virtual ICollection<FamilyTree> FamilyTrees { get; set; }
        public virtual ICollection<LendAHand> LendAHands { get; set; }
        public virtual TermsMaster TermsMaster { get; set; }
        public virtual ICollection<Timeline> Timelines { get; set; }
        public virtual ICollection<ContributionDetail> ContributionDetails { get; set; }
        public virtual ICollection<Nominee> Nominees { get; set; }
        public virtual ICollection<Nominee> Nominees1 { get; set; }
        public virtual ICollection<UserComment> UserComments { get; set; }
        public virtual ICollection<UserContactDetail> UserContactDetails { get; set; }
        public virtual ICollection<UserPersonalDetail> UserPersonalDetails { get; set; }
        public virtual ICollection<UserComment> UserComments1 { get; set; }
        public virtual ICollection<Announcement> Announcements1 { get; set; }
    }
}
